### ISSUE TITLE
Invalid promoting permissions.

### ISSUE THREAD

**Issue by ghost** [FroastJ/roblox-bots#16]
There seems to be a problem with '**changeRank.php**'. 

Whenever I try to promote a player it gives me the error '_Invalid promoting permissions_'. Yet when I try '**shout.php**' it works. I'm not exactly sure what causes the problem since I'm pretty sure I did and followed the instructions correctly. 

Also I noticed that when I manually tried (not sure if this is the correct way to do it) _http://www.roblox.com/groups/api/change-member-rank?groupId=1068188&newRoleSetId=6&targetUserId=62387413_ it ended up with the error 404? Could it be that ROBLOX changed their APIs or is there something wrong on my end?

![0ca6a8e22fb6888cd21d9403668462e2](https://cloud.githubusercontent.com/assets/17051217/15100714/67b9c9c6-1583-11e6-9da2-fb2c871ffd29.png)

**Comment by sentanos** [comment]
I have tested the function and confirmed that it is still working, this is most likely a problem on your end. First of all, when you say "shout worked", do you mean when you send the request to the server it comes back saying it worked or you actually see the shout in the group? Unlike updateRank, shout does not check if the shout was actually successful: if the page loaded it returns a success message.

If the shout is not actually showing up, please refer to [#issuecomment-188284257](https://github.com/FroastJ/roblox-bots/issues/12#issuecomment-188284257) to fix login issues.
Otherwise, these are what you should check:
- Make sure all parameters are correct, both when the function is called and when you send the request to your server. If a rank or user doesn't exist the function will fail
- Make sure the user you are logged in to actually has permission to promote the target user, there are actually many people that forget to give the necessary permissions to their bot

**Comment by ghost** [comment]
Yeah, when I tested the shout it worked perfectly and I could see the shout in the group as well. I tried manually promoting few players with the bot account and it worked that means that bot has the necessary permissions. I'm pretty sure my parameters are correct:

`{
    "Validate":"1234", -- PostKey
    "Action":"setRank", -- Action
    "Parameter1":"76314425", -- User ID
    "Parameter2":"6" -- Rank I want to promote him to
}`

Here are the ranks/roles of the group. The bot is 'Club Manager'.
![f6d9e63697274b1536db45509146dfe8](https://cloud.githubusercontent.com/assets/17051217/15106758/1c35ddea-15d4-11e6-89ff-753cfeee5fc8.png)

I'll keep on trying, thanks for the answer!

**Comment by Gskartwii** [comment]
The issue here is that you're passing a rank ID instead of a roleset ID. There is some API to get the roleset ID, but I can't remember where.

**Comment by sentanos** [comment]
@Gskartwii 
Assuming @Zcython is using the function correctly on his server (or using the recommended [receiver.php](https://github.com/FroastJ/roblox-bots/blob/master/Examples/receiver.php)), the matching rolesetID should be retrieved automatically.

The script calling updateRanks should retrieve an array of rolesets and an array of ranks from the `getRoleSets` function before passing it to updateRank, which will then match the rank up to the roleset.

``` php
list($ranks,$roles) =   getRoleSets($group);
```

Absolutely horrible setup, I know, but at the moment I can't be bothered to rewrite the entire project .

**Comment by ghost** [comment]
Fixed it. 
The problem was with the group rank names. I had to remove the symbols from them and then it worked perfectly, thanks for the help @FroastJ , @Gskartwii !

**Comment by sentanos** [comment]
Great thing that you got it fixed but in that case it's still a problem that the script won't work if the rank names have symbols. Unfortunately I have not been able to replicate the problem myself with similar symbols. If you could provide the exact rank names I'll replicate it exactly and try to fix the error.

**Comment by ghost** [comment]
Sure thing, here you go: ╡╞ 
Ranks that I had previously: ╡Bartender╞, ╡DJ╞, ╡Attender╞ etc.
Hopefully, you can fix the error! :+1:

**Comment by sentanos** [comment]
@Zcython Do you have the separator rank names?

**Comment by ghost** [comment]
Yeah, for them I use the symbol: ▬▬▬▬▬▬
I _usually_ don't promote people to that rank.
